#!/bin/bash
#author: Timur Bas <maox123@hotmail.com>

#Basic mathematics in bash
NUMBER=1905

echo "What is 1905 plus 532?"
echo "That must equal: $((NUMBER+532))"

echo "What is 1905 subtracted by 532?"
echo "That must equal: $((NUMBER-532))"

echo "What is 1905 divided by 532?"
#TO-DO find out how to calculate floats/doubles
